### ISSUE TITLE
"Save and duplicate" button does not work everywhere

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2323]
- Contao 4.13.6
- PHP 8.1
- Isotope 2.8.5

I noticed that the «Save and duplicate» button does not always work correctly.

Especially in the store configuration, it happens almost everywhere that after clicking the button I only end up in the overview and nothing is duplicated.

**Steps to reproduce the error**
1. create new shipping method 
2. Save and duplicate

This also happens among others:
- tax rates
- tax classes
- shipping methods
- payment methods
- attributes
- product types

**Comment by aschempp** [comment]
Can you test if this has been fixed in the latest dev branch (specifically by daee4bc776295e00b48506a2a5cbccfecb401188)?

**Comment by contaoacademy** [comment]
I have installed `2.8.x-dev`, but there the problem persists.

**Comment by aschempp** [comment]
I just tested this in the latest version and was unable to reproduce. Let me know if you still experience it.

**Comment by contaoacademy** [comment]
The problem still persists for me in Contao Version 4.13.16, PHP 8.1 and Isotope 2.8.10.
Save and duplicate doesn't work.

**Comment by aschempp** [comment]
Finally fixed in 284ae45709eaa797e7e8eace9d6c82f1f680773e

**Comment by contaoacademy** [comment]
I don't get it. For me, the problem is still there with 2.8.11.
